      - name: Ejecutar Dependency-Check en frontend/digiturno-app
        run: |
          docker run --rm \
            -e NVD_API_KEY=${{ secrets.NVD_API_KEY }} \
            -v ${{ github.workspace }}/frontend/digiturno-app:/src \
            owasp/dependency-check \
            --project "Digiturno Frontend" \
            --scan /src \
            --format "HTML" \
            --out /src/dependency-check-report
