name: Análisis de dependencias (OWASP) - Frontend

on:
  push:
    paths:
      - 'frontend/digiturno-app/**'
  pull_request:
    paths:
      - 'frontend/digiturno-app/**'

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Ejecutar Dependency-Check en frontend/digiturno-app
        run: |
          docker run --rm \
            -e NVD_API_KEY=${{ secrets.NVD_API_KEY }} \
            -v ${{ github.workspace }}/frontend/digiturno-app:/src \
            owasp/dependency-check \
            --project "Digiturno Frontend" \
            --scan /src \
            --format "HTML" \
            --out /src/dependency-check-report

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: Reporte-OWASP-Frontend
          path: frontend/digiturno-app/dependency-check-report


